import {
  FileArchive, FileStack, Scissors, FileText, FileType, Image as ImageIcon,
  ScanLine, Unlock, Lock, Droplets, RotateCw, Hash, Trash2, ArrowDownUp, PenTool, BookOpen,
} from "lucide-react";

export type Tool = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  icon: typeof FileArchive;
  gradient: string;
  accept: string;
  multiple: boolean;
  category?: "Optimize" | "Organize" | "Convert" | "Edit" | "Security" | "View";
};

export const tools: Tool[] = [
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    tagline: "Reduce PDF size without losing quality",
    description: "Shrink PDF files quickly while keeping documents readable. Perfect for email attachments and uploads.",
    icon: FileArchive,
    gradient: "from-indigo-500 to-violet-500",
    accept: "application/pdf",
    multiple: false,
    category: "Optimize",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    tagline: "Combine multiple PDFs into one",
    description: "Drag and drop several PDFs and merge them into a single, well-ordered document in seconds.",
    icon: FileStack,
    gradient: "from-violet-500 to-fuchsia-500",
    accept: "application/pdf",
    multiple: true,
    category: "Organize",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    tagline: "Extract pages from a PDF",
    description: "Split a PDF by page ranges and download separate documents in a single click.",
    icon: Scissors,
    gradient: "from-fuchsia-500 to-pink-500",
    accept: "application/pdf",
    multiple: false,
    category: "Organize",
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    tagline: "Convert PDF text to Word",
    description: "Extract text from your PDF and download it as an editable Word (.docx) document.",
    icon: FileText,
    gradient: "from-blue-500 to-indigo-500",
    accept: "application/pdf",
    multiple: false,
    category: "Convert",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    tagline: "Convert Word documents to PDF",
    description: "Turn your .docx files into clean, share-ready PDFs — directly in the browser.",
    icon: FileType,
    gradient: "from-emerald-500 to-teal-500",
    accept: ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    multiple: false,
    category: "Convert",
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    tagline: "Combine images into a PDF",
    description: "Convert JPG, PNG and WebP images into a single PDF document, ready to share or print.",
    icon: ImageIcon,
    gradient: "from-amber-500 to-orange-500",
    accept: "image/jpeg,image/png,image/webp",
    multiple: true,
    category: "Convert",
  },
  {
    slug: "ocr-pdf",
    name: "OCR PDF",
    tagline: "Extract editable text from scanned PDFs",
    description: "Run optical character recognition on scanned PDFs or images to extract editable text right in your browser.",
    icon: ScanLine,
    gradient: "from-cyan-500 to-blue-500",
    accept: "application/pdf,image/jpeg,image/png",
    multiple: false,
    category: "Convert",
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    tagline: "Remove password from a PDF",
    description: "Remove password restrictions from PDFs you legally own. Files are processed securely in your browser.",
    icon: Unlock,
    gradient: "from-lime-500 to-emerald-500",
    accept: "application/pdf",
    multiple: false,
    category: "Security",
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    tagline: "Add password protection to a PDF",
    description: "Encrypt your PDF with a password to control who can open and view your document.",
    icon: Lock,
    gradient: "from-red-500 to-rose-500",
    accept: "application/pdf",
    multiple: false,
    category: "Security",
  },
  {
    slug: "watermark-pdf",
    name: "Watermark PDF",
    tagline: "Add a custom text watermark",
    description: "Stamp every page of your PDF with a customizable text watermark — opacity, position and rotation included.",
    icon: Droplets,
    gradient: "from-sky-500 to-cyan-500",
    accept: "application/pdf",
    multiple: false,
    category: "Edit",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    tagline: "Rotate pages 90°, 180° or 270°",
    description: "Rotate every page or selected pages of your PDF and save the result instantly.",
    icon: RotateCw,
    gradient: "from-orange-500 to-red-500",
    accept: "application/pdf",
    multiple: false,
    category: "Edit",
  },
  {
    slug: "page-numbers",
    name: "Page Numbers",
    tagline: "Add page numbering to a PDF",
    description: "Automatically add clean, customizable page numbers to your PDF documents.",
    icon: Hash,
    gradient: "from-purple-500 to-indigo-500",
    accept: "application/pdf",
    multiple: false,
    category: "Edit",
  },
  {
    slug: "delete-pages",
    name: "Delete Pages",
    tagline: "Remove pages from a PDF",
    description: "Quickly delete unwanted pages from your PDF with a visual page picker.",
    icon: Trash2,
    gradient: "from-rose-500 to-red-500",
    accept: "application/pdf",
    multiple: false,
    category: "Organize",
  },
  {
    slug: "reorder-pages",
    name: "Reorder Pages",
    tagline: "Drag and drop to reorder pages",
    description: "Rearrange the pages of your PDF with smooth drag-and-drop and download the reordered file.",
    icon: ArrowDownUp,
    gradient: "from-teal-500 to-emerald-500",
    accept: "application/pdf",
    multiple: false,
    category: "Organize",
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    tagline: "Add your signature to a PDF",
    description: "Draw or upload your signature and place it on any page of your PDF, all in your browser.",
    icon: PenTool,
    gradient: "from-pink-500 to-rose-500",
    accept: "application/pdf",
    multiple: false,
    category: "Edit",
  },
  {
    slug: "pdf-reader",
    name: "PDF Reader",
    tagline: "Preview PDFs with zoom controls",
    description: "Open and read PDFs directly in your browser with smooth, fast rendering and zoom controls.",
    icon: BookOpen,
    gradient: "from-slate-500 to-gray-700",
    accept: "application/pdf",
    multiple: false,
    category: "View",
  },
];

export const getTool = (slug: string) => tools.find((t) => t.slug === slug)!;
